//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TdService.Domain
{
    public class Product
	{
		public virtual int Quantity { get; set; }

		public virtual string ProductName { get; set; }

		public virtual Price Price { get; set; }

		public virtual int Id { get; set; }
	}
}