// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.17929
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TdService.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Delivery Addresses")]
    [NUnit.Framework.CategoryAttribute("deliveryaddresses")]
    public partial class DeliveryAddressesFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "DeliveryAddresses.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Delivery Addresses", "In order to choose delivery address for my packages\r\nAs a shopper\r\nI want to be a" +
                    "ble to view, add, edit and remove my delivery addresses", ProgrammingLanguage.CSharp, new string[] {
                        "deliveryaddresses"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("View own delivery addresses")]
        [NUnit.Framework.CategoryAttribute("viewdeliveryaddresses")]
        public virtual void ViewOwnDeliveryAddresses()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("View own delivery addresses", new string[] {
                        "viewdeliveryaddresses"});
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("I have \'v.hatalski@gmail.com\' email address", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "FirstName",
                        "LastName",
                        "AddressName",
                        "AddressLine1",
                        "AddressLine2",
                        "City",
                        "Country",
                        "State",
                        "Region",
                        "ZipCode",
                        "Phone"});
            table1.AddRow(new string[] {
                        "1",
                        "Vitali",
                        "Hatalski",
                        "Minsk - Novovilenskaya",
                        "Novovilenskaya street",
                        "10, 41",
                        "Minsk",
                        "Belarus",
                        "",
                        "",
                        "220053",
                        "+375295067630"});
            table1.AddRow(new string[] {
                        "2",
                        "Vitali",
                        "Hatalski",
                        "Minsk - Nekrasova",
                        "Nekrasova street",
                        "8, 14",
                        "Minsk",
                        "Belarus",
                        "",
                        "",
                        "220040",
                        "+375295067630"});
            table1.AddRow(new string[] {
                        "3",
                        "Patric",
                        "Gutie",
                        "France - Paris",
                        "Elisei",
                        "14/3, 45",
                        "Paris",
                        "France",
                        "",
                        "",
                        "12040",
                        "+455295067630"});
#line 10
 testRunner.And("I have the following delivery addresses", ((string)(null)), table1, "And ");
#line 15
 testRunner.When("I get my own delivery addresses", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "FirstName",
                        "LastName",
                        "AddressName",
                        "AddressLine1",
                        "AddressLine2",
                        "City",
                        "Country",
                        "State",
                        "Region",
                        "ZipCode",
                        "Phone"});
            table2.AddRow(new string[] {
                        "1",
                        "Vitali",
                        "Hatalski",
                        "Minsk - Novovilenskaya",
                        "Novovilenskaya street",
                        "10, 41",
                        "Minsk",
                        "Belarus",
                        "",
                        "",
                        "220053",
                        "+375295067630"});
            table2.AddRow(new string[] {
                        "2",
                        "Vitali",
                        "Hatalski",
                        "Minsk - Nekrasova",
                        "Nekrasova street",
                        "8, 14",
                        "Minsk",
                        "Belarus",
                        "",
                        "",
                        "220040",
                        "+375295067630"});
            table2.AddRow(new string[] {
                        "3",
                        "Patric",
                        "Gutie",
                        "France - Paris",
                        "Elisei",
                        "14/3, 45",
                        "Paris",
                        "France",
                        "",
                        "",
                        "12040",
                        "+455295067630"});
#line 16
 testRunner.Then("I should have the following delivery addresses as a result", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add delivery address")]
        [NUnit.Framework.CategoryAttribute("adddeliveryaddress")]
        public virtual void AddDeliveryAddress()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add delivery address", new string[] {
                        "adddeliveryaddress"});
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
 testRunner.Given("I have \'v.hatalski@gmail.com\' email address", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "FirstName",
                        "LastName",
                        "AddressName",
                        "AddressLine1",
                        "AddressLine2",
                        "City",
                        "Country",
                        "State",
                        "Region",
                        "ZipCode",
                        "Phone",
                        "MessageType"});
            table3.AddRow(new string[] {
                        "1",
                        "Vitali",
                        "Hatalski",
                        "Initial",
                        "Nekrasova 8",
                        "flat 14",
                        "Minsk",
                        "Belarus",
                        "",
                        "",
                        "220040",
                        "",
                        ""});
#line 25
 testRunner.And("I have the following delivery addresses", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "FirstName",
                        "LastName",
                        "AddressName",
                        "AddressLine1",
                        "AddressLine2",
                        "City",
                        "Country",
                        "State",
                        "Region",
                        "ZipCode",
                        "Phone",
                        "MessageType"});
            table4.AddRow(new string[] {
                        "",
                        "Vitali",
                        "Hatalski",
                        "My first",
                        "Nekrasova 8",
                        "flat 14",
                        "Minsk",
                        "Belarus",
                        "",
                        "",
                        "220040",
                        "",
                        ""});
            table4.AddRow(new string[] {
                        "",
                        "Vitali",
                        "Hatalski",
                        "My second",
                        "Novovilenskaya 10",
                        "flat 41",
                        "Minsk",
                        "Belarus",
                        "",
                        "",
                        "220053",
                        "+375295067630",
                        ""});
            table4.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "My second",
                        "Novovilenskaya 10",
                        "flat 41",
                        "Minsk",
                        "Belarus",
                        "",
                        "",
                        "220053",
                        "+375295067630",
                        ""});
#line 28
 testRunner.When("I add the following delivery addresses", ((string)(null)), table4, "When ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "FirstName",
                        "LastName",
                        "AddressName",
                        "AddressLine1",
                        "AddressLine2",
                        "City",
                        "Country",
                        "State",
                        "Region",
                        "ZipCode",
                        "Phone",
                        "MessageType"});
            table5.AddRow(new string[] {
                        "2",
                        "Vitali",
                        "Hatalski",
                        "My first",
                        "Nekrasova 8",
                        "flat 14",
                        "Minsk",
                        "Belarus",
                        "",
                        "",
                        "220040",
                        "",
                        "Success"});
            table5.AddRow(new string[] {
                        "3",
                        "Vitali",
                        "Hatalski",
                        "My second",
                        "Novovilenskaya 10",
                        "flat 41",
                        "Minsk",
                        "Belarus",
                        "",
                        "",
                        "220053",
                        "+375295067630",
                        "Success"});
            table5.AddRow(new string[] {
                        "0",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "Error"});
#line 33
 testRunner.Then("I should have the following delivery addresses as a result", ((string)(null)), table5, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Edit delivery address")]
        [NUnit.Framework.CategoryAttribute("editdeliveryaddress")]
        public virtual void EditDeliveryAddress()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Edit delivery address", new string[] {
                        "editdeliveryaddress"});
#line 40
this.ScenarioSetup(scenarioInfo);
#line 41
 testRunner.Given("I have \'v.hatalski@gmail.com\' email address", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "FirstName",
                        "LastName",
                        "AddressName",
                        "AddressLine1",
                        "AddressLine2",
                        "City",
                        "Country",
                        "State",
                        "Region",
                        "ZipCode",
                        "Phone",
                        "MessageType"});
            table6.AddRow(new string[] {
                        "1",
                        "Vitali",
                        "Hatalski",
                        "My first",
                        "Nekrasova 8",
                        "flat 14",
                        "Minsk",
                        "Belarus",
                        "",
                        "",
                        "220040",
                        "",
                        ""});
            table6.AddRow(new string[] {
                        "2",
                        "Vitali",
                        "Hatalski",
                        "My second",
                        "Novovilenskaya 10",
                        "flat 41",
                        "Minsk",
                        "Belarus",
                        "",
                        "",
                        "220053",
                        "+375295067630",
                        ""});
#line 42
 testRunner.And("I have the following delivery addresses", ((string)(null)), table6, "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "FirstName",
                        "LastName",
                        "AddressName",
                        "AddressLine1",
                        "AddressLine2",
                        "City",
                        "Country",
                        "State",
                        "Region",
                        "ZipCode",
                        "Phone",
                        "MessageType"});
            table7.AddRow(new string[] {
                        "1",
                        "",
                        "Hatalski",
                        "My first",
                        "Nekrasova 8",
                        "flat 14",
                        "Minsk",
                        "Belarus",
                        "",
                        "",
                        "220040",
                        "",
                        ""});
            table7.AddRow(new string[] {
                        "2",
                        "Alex",
                        "Hatalski",
                        "Main address",
                        "Nekrasova 8",
                        "flat 14",
                        "Minsk",
                        "Belarus",
                        "",
                        "",
                        "220040",
                        "",
                        ""});
#line 46
 testRunner.When("I edit the following delivery addresses", ((string)(null)), table7, "When ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "FirstName",
                        "LastName",
                        "AddressName",
                        "AddressLine1",
                        "AddressLine2",
                        "City",
                        "Country",
                        "State",
                        "Region",
                        "ZipCode",
                        "Phone",
                        "MessageType"});
            table8.AddRow(new string[] {
                        "1",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "Error"});
            table8.AddRow(new string[] {
                        "2",
                        "Alex",
                        "Hatalski",
                        "Main address",
                        "Nekrasova 8",
                        "flat 14",
                        "Minsk",
                        "Belarus",
                        "",
                        "",
                        "220040",
                        "",
                        "Success"});
#line 50
 testRunner.Then("I should have the following delivery addresses as a result", ((string)(null)), table8, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Remove delivery address")]
        [NUnit.Framework.CategoryAttribute("removedeliveryaddress")]
        public virtual void RemoveDeliveryAddress()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Remove delivery address", new string[] {
                        "removedeliveryaddress"});
#line 56
this.ScenarioSetup(scenarioInfo);
#line 57
 testRunner.Given("I have \'v.hatalski@gmail.com\' email address", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "FirstName",
                        "LastName",
                        "AddressName",
                        "AddressLine1",
                        "AddressLine2",
                        "City",
                        "Country",
                        "State",
                        "Region",
                        "ZipCode",
                        "Phone",
                        "MessageType"});
            table9.AddRow(new string[] {
                        "1",
                        "Vitali",
                        "Hatalski",
                        "My first",
                        "Nekrasova 8",
                        "flat 14",
                        "Minsk",
                        "Belarus",
                        "",
                        "",
                        "220040",
                        "",
                        ""});
            table9.AddRow(new string[] {
                        "2",
                        "Vitali",
                        "Hatalski",
                        "My second",
                        "Novovilenskaya 10",
                        "flat 41",
                        "Minsk",
                        "Belarus",
                        "",
                        "",
                        "220053",
                        "+375295067630",
                        ""});
#line 58
 testRunner.And("I have the following delivery addresses", ((string)(null)), table9, "And ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id"});
            table10.AddRow(new string[] {
                        "1"});
#line 62
 testRunner.When("I remove the following delivery addresses", ((string)(null)), table10, "When ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "FirstName",
                        "LastName",
                        "AddressName",
                        "AddressLine1",
                        "AddressLine2",
                        "City",
                        "Country",
                        "State",
                        "Region",
                        "ZipCode",
                        "Phone",
                        "MessageType"});
            table11.AddRow(new string[] {
                        "1",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "Success"});
#line 65
 testRunner.Then("I should have the following delivery addresses as a result", ((string)(null)), table11, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
