// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.17929
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TdService.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Shopper Orders")]
    [NUnit.Framework.CategoryAttribute("orders")]
    public partial class ShopperOrdersFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ShopperOrders.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Shopper Orders", "In order to let operator know about incoming orders\r\nAs a shopper\r\nI want to be a" +
                    "ble to add new orders, remove them and update with tracking number and order num" +
                    "ber", ProgrammingLanguage.CSharp, new string[] {
                        "orders"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("View my recent orders")]
        [NUnit.Framework.CategoryAttribute("viewrecentorders")]
        public virtual void ViewMyRecentOrders()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("View my recent orders", new string[] {
                        "viewrecentorders"});
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Shopper" +
                    "\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer",
                        "Order Number",
                        "Tracking Number",
                        "Status"});
            table1.AddRow(new string[] {
                        "1",
                        "amazon.com",
                        "",
                        "773456789012345",
                        "New"});
            table1.AddRow(new string[] {
                        "2",
                        "6pm.com",
                        "123453453455",
                        "673456789012345",
                        "Received"});
            table1.AddRow(new string[] {
                        "3",
                        "zazzle.com",
                        "125675575445",
                        "344567895675664",
                        "Returned"});
            table1.AddRow(new string[] {
                        "4",
                        "yoox.com",
                        "455367456655",
                        "34567893442345",
                        "Disposed"});
            table1.AddRow(new string[] {
                        "5",
                        "zappos.com",
                        "234345454433",
                        "123456789012345",
                        "Received"});
            table1.AddRow(new string[] {
                        "6",
                        "zappos.com",
                        "453656457544",
                        "245763453445463",
                        "ReturnRequested"});
#line 11
 testRunner.And("I have the following orders", ((string)(null)), table1, "And ");
#line 19
 testRunner.When("I go to my recent orders tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer Url",
                        "Order Number",
                        "Tracking Number",
                        "Status",
                        "Can Be Modified",
                        "Can Be Removed",
                        "Can Be Requested For Return",
                        "Can Items Be Modified",
                        "Message Type"});
            table2.AddRow(new string[] {
                        "1",
                        "amazon.com",
                        "",
                        "773456789012345",
                        "New",
                        "True",
                        "True",
                        "False",
                        "True",
                        "Success"});
            table2.AddRow(new string[] {
                        "2",
                        "6pm.com",
                        "123453453455",
                        "673456789012345",
                        "Received",
                        "False",
                        "False",
                        "True",
                        "False",
                        "Success"});
            table2.AddRow(new string[] {
                        "5",
                        "zappos.com",
                        "234345454433",
                        "123456789012345",
                        "Received",
                        "False",
                        "False",
                        "True",
                        "False",
                        "Success"});
            table2.AddRow(new string[] {
                        "6",
                        "zappos.com",
                        "453656457544",
                        "245763453445463",
                        "ReturnRequested",
                        "False",
                        "False",
                        "False",
                        "False",
                        "Success"});
#line 20
 testRunner.Then("the order view models should be as follows", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("View my history orders")]
        [NUnit.Framework.CategoryAttribute("viewhistoryorders")]
        public virtual void ViewMyHistoryOrders()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("View my history orders", new string[] {
                        "viewhistoryorders"});
#line 28
this.ScenarioSetup(scenarioInfo);
#line 29
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Shopper" +
                    "\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 30
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer",
                        "Order Number",
                        "Tracking Number",
                        "Status"});
            table3.AddRow(new string[] {
                        "1",
                        "amazon.com",
                        "",
                        "773456789012345",
                        "New"});
            table3.AddRow(new string[] {
                        "2",
                        "6pm.com",
                        "123453453455",
                        "673456789012345",
                        "Received"});
            table3.AddRow(new string[] {
                        "3",
                        "zazzle.com",
                        "125675575445",
                        "344567895675664",
                        "Returned"});
            table3.AddRow(new string[] {
                        "4",
                        "yoox.com",
                        "455367456655",
                        "34567893442345",
                        "Disposed"});
            table3.AddRow(new string[] {
                        "5",
                        "zappos.com",
                        "234345454433",
                        "123456789012345",
                        "Received"});
            table3.AddRow(new string[] {
                        "6",
                        "zappos.com",
                        "453656457544",
                        "245763453445463",
                        "ReturnRequested"});
#line 31
 testRunner.And("I have the following orders", ((string)(null)), table3, "And ");
#line 39
 testRunner.When("I go to my history orders tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer Url",
                        "Order Number",
                        "Tracking Number",
                        "Status",
                        "Can Be Modified",
                        "Can Be Removed",
                        "Can Be Requested For Return",
                        "Can Items Be Modified",
                        "Message Type"});
            table4.AddRow(new string[] {
                        "3",
                        "zazzle.com",
                        "125675575445",
                        "344567895675664",
                        "Returned",
                        "False",
                        "False",
                        "False",
                        "False",
                        "Success"});
            table4.AddRow(new string[] {
                        "4",
                        "yoox.com",
                        "455367456655",
                        "34567893442345",
                        "Disposed",
                        "False",
                        "False",
                        "False",
                        "False",
                        "Success"});
#line 40
 testRunner.Then("the order view models should be as follows", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add new order should be possible by shopper")]
        [NUnit.Framework.CategoryAttribute("addorder")]
        public virtual void AddNewOrderShouldBePossibleByShopper()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add new order should be possible by shopper", new string[] {
                        "addorder"});
#line 46
this.ScenarioSetup(scenarioInfo);
#line 47
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Shopper" +
                    "\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 48
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
 testRunner.When("I set retailer url as \'amazon.com\' and press add order button on shopper dashboar" +
                    "d page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer Url",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status",
                        "Can Be Modified",
                        "Can Be Removed",
                        "Can Be Requested For Return",
                        "Can Items Be Modified",
                        "Message Type"});
            table5.AddRow(new string[] {
                        "1",
                        "amazon.com",
                        "",
                        "",
                        "",
                        "New",
                        "True",
                        "True",
                        "False",
                        "True",
                        "Success"});
#line 50
 testRunner.Then("the order view model should be as follows", ((string)(null)), table5, "Then ");
#line 53
 testRunner.And("the order view model should have Created Date that is earlier than UTC Now", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add new order should not be possible by operator")]
        [NUnit.Framework.CategoryAttribute("addorder")]
        public virtual void AddNewOrderShouldNotBePossibleByOperator()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add new order should not be possible by operator", new string[] {
                        "addorder"});
#line 56
this.ScenarioSetup(scenarioInfo);
#line 57
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Operato" +
                    "r\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 58
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
 testRunner.When("I set retailer url as \'amazon.com\' and press add order button on shopper dashboar" +
                    "d page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer Url",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status",
                        "Message Type",
                        "Error Code"});
            table6.AddRow(new string[] {
                        "0",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "Error",
                        "OrderCannotBeAddedByYou"});
#line 60
 testRunner.Then("the order view model should be as follows", ((string)(null)), table6, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add new order should not be possible by consultant")]
        [NUnit.Framework.CategoryAttribute("addorder")]
        public virtual void AddNewOrderShouldNotBePossibleByConsultant()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add new order should not be possible by consultant", new string[] {
                        "addorder"});
#line 65
this.ScenarioSetup(scenarioInfo);
#line 66
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Consult" +
                    "ant\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 67
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 68
 testRunner.When("I set retailer url as \'amazon.com\' and press add order button on shopper dashboar" +
                    "d page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer Url",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status",
                        "Message Type",
                        "Error Code"});
            table7.AddRow(new string[] {
                        "0",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "Error",
                        "OrderCannotBeAddedByYou"});
#line 69
 testRunner.Then("the order view model should be as follows", ((string)(null)), table7, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add new order should not be possible by admin")]
        [NUnit.Framework.CategoryAttribute("addorder")]
        public virtual void AddNewOrderShouldNotBePossibleByAdmin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add new order should not be possible by admin", new string[] {
                        "addorder"});
#line 74
this.ScenarioSetup(scenarioInfo);
#line 75
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Admin\' " +
                    "with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 76
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 77
 testRunner.When("I set retailer url as \'amazon.com\' and press add order button on shopper dashboar" +
                    "d page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer Url",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status",
                        "Message Type",
                        "Error Code"});
            table8.AddRow(new string[] {
                        "0",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "Error",
                        "OrderCannotBeAddedByYou"});
#line 78
 testRunner.Then("the order view model should be as follows", ((string)(null)), table8, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add new order reusing existent retailer instead of creating new one")]
        [NUnit.Framework.CategoryAttribute("addorder")]
        public virtual void AddNewOrderReusingExistentRetailerInsteadOfCreatingNewOne()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add new order reusing existent retailer instead of creating new one", new string[] {
                        "addorder"});
#line 83
this.ScenarioSetup(scenarioInfo);
#line 84
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Shopper" +
                    "\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 85
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer",
                        "Order Number",
                        "Tracking Number",
                        "Status"});
            table9.AddRow(new string[] {
                        "1",
                        "amazon.com",
                        "",
                        "773456789012345",
                        "New"});
#line 86
 testRunner.And("I have the following orders", ((string)(null)), table9, "And ");
#line 89
 testRunner.When("I set retailer url as \'amazon.com\' and press add order button on shopper dashboar" +
                    "d page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer Url",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status",
                        "Can Be Modified",
                        "Can Be Removed",
                        "Can Be Requested For Return",
                        "Can Items Be Modified",
                        "Message Type"});
            table10.AddRow(new string[] {
                        "2",
                        "amazon.com",
                        "",
                        "",
                        "",
                        "New",
                        "True",
                        "True",
                        "False",
                        "True",
                        "Success"});
#line 90
 testRunner.Then("the order view model should be as follows", ((string)(null)), table10, "Then ");
#line 93
 testRunner.And("there must be only one db record with \'amazon.com\' retailer url", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add new order validate retailer url is required")]
        [NUnit.Framework.CategoryAttribute("addorder")]
        public virtual void AddNewOrderValidateRetailerUrlIsRequired()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add new order validate retailer url is required", new string[] {
                        "addorder"});
#line 96
this.ScenarioSetup(scenarioInfo);
#line 97
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Shopper" +
                    "\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 98
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 99
 testRunner.When("I set retailer url as \'\' and press add order button on shopper dashboard page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer Url",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status",
                        "Can Be Modified",
                        "Can Be Removed",
                        "Can Be Requested For Return",
                        "Can Items Be Modified",
                        "Message Type"});
            table11.AddRow(new string[] {
                        "0",
                        "",
                        "",
                        "",
                        "",
                        "New",
                        "False",
                        "False",
                        "False",
                        "False",
                        "Warning"});
#line 100
 testRunner.Then("the order view model should be as follows", ((string)(null)), table11, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Error Code"});
            table12.AddRow(new string[] {
                        "RetailerUrl",
                        "OrderRetailerRequired"});
#line 103
 testRunner.And("the order view model should have the following errors", ((string)(null)), table12, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add new order validate retailer max length")]
        [NUnit.Framework.CategoryAttribute("addorder")]
        public virtual void AddNewOrderValidateRetailerMaxLength()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add new order validate retailer max length", new string[] {
                        "addorder"});
#line 108
this.ScenarioSetup(scenarioInfo);
#line 109
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Shopper" +
                    "\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 110
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 111
 testRunner.When(@"I set retailer url as 'this is the very long an unusual retailer url that is not actually a url but a long text that exceeds the maximum allowed length for url addresses this is the very long an unusual retailer url that is not actually a url but a long text that exceeds the maximum allowed length for url addresses' and press add order button on shopper dashboard page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer Url",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status",
                        "Can Be Modified",
                        "Can Be Removed",
                        "Can Be Requested For Return",
                        "Can Items Be Modified",
                        "Message Type"});
            table13.AddRow(new string[] {
                        "0",
                        @"this is the very long an unusual retailer url that is not actually a url but a long text that exceeds the maximum allowed length for url addresses this is the very long an unusual retailer url that is not actually a url but a long text that exceeds the maximum allowed length for url addresses",
                        "",
                        "",
                        "",
                        "New",
                        "False",
                        "False",
                        "False",
                        "False",
                        "Warning"});
#line 112
 testRunner.Then("the order view model should be as follows", ((string)(null)), table13, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Error Code"});
            table14.AddRow(new string[] {
                        "RetailerUrl",
                        "RetailerUrlMaxLength"});
#line 115
 testRunner.And("the order view model should have the following errors", ((string)(null)), table14, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update order in new status should be possible by shopper")]
        [NUnit.Framework.CategoryAttribute("updateorder")]
        public virtual void UpdateOrderInNewStatusShouldBePossibleByShopper()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update order in new status should be possible by shopper", new string[] {
                        "updateorder"});
#line 120
this.ScenarioSetup(scenarioInfo);
#line 121
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Shopper" +
                    "\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 122
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer",
                        "Order Number",
                        "Tracking Number",
                        "Status"});
            table15.AddRow(new string[] {
                        "1",
                        "amazon.com",
                        "",
                        "123456789012345",
                        "New"});
#line 123
 testRunner.And("I have the following orders", ((string)(null)), table15, "And ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Order Number",
                        "Tracking Number",
                        "Status"});
            table16.AddRow(new string[] {
                        "1",
                        "098765432109",
                        "1234",
                        "New"});
#line 126
 testRunner.When("I update order as follows", ((string)(null)), table16, "When ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Order Number",
                        "Tracking Number",
                        "Status",
                        "Message Type"});
            table17.AddRow(new string[] {
                        "1",
                        "098765432109",
                        "1234",
                        "New",
                        "Success"});
#line 129
 testRunner.Then("the order view model should be as follows", ((string)(null)), table17, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update order in new status should be possible by operator")]
        [NUnit.Framework.CategoryAttribute("updateorder")]
        public virtual void UpdateOrderInNewStatusShouldBePossibleByOperator()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update order in new status should be possible by operator", new string[] {
                        "updateorder"});
#line 134
this.ScenarioSetup(scenarioInfo);
#line 135
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Operato" +
                    "r\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 136
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer",
                        "Order Number",
                        "Tracking Number",
                        "Status"});
            table18.AddRow(new string[] {
                        "1",
                        "amazon.com",
                        "",
                        "123456789012345",
                        "New"});
#line 137
 testRunner.And("I have the following orders", ((string)(null)), table18, "And ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Order Number",
                        "Tracking Number",
                        "Status"});
            table19.AddRow(new string[] {
                        "1",
                        "098765432109",
                        "1234",
                        "New"});
#line 140
 testRunner.When("I update order as follows", ((string)(null)), table19, "When ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Order Number",
                        "Tracking Number",
                        "Status",
                        "Message Type"});
            table20.AddRow(new string[] {
                        "1",
                        "098765432109",
                        "1234",
                        "New",
                        "Success"});
#line 143
 testRunner.Then("the order view model should be as follows", ((string)(null)), table20, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update order in any other status than New should not be possible")]
        [NUnit.Framework.CategoryAttribute("updateorder")]
        public virtual void UpdateOrderInAnyOtherStatusThanNewShouldNotBePossible()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update order in any other status than New should not be possible", new string[] {
                        "updateorder"});
#line 148
this.ScenarioSetup(scenarioInfo);
#line 149
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Shopper" +
                    "\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 150
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer",
                        "Order Number",
                        "Tracking Number",
                        "Status"});
            table21.AddRow(new string[] {
                        "1",
                        "amazon.com",
                        "",
                        "123456789012345",
                        "Received"});
            table21.AddRow(new string[] {
                        "2",
                        "amazon.com",
                        "",
                        "123456789012345",
                        "Disposed"});
            table21.AddRow(new string[] {
                        "3",
                        "amazon.com",
                        "",
                        "123456789012345",
                        "Returned"});
            table21.AddRow(new string[] {
                        "4",
                        "amazon.com",
                        "",
                        "123456789012345",
                        "ReturnRequested"});
#line 151
 testRunner.And("I have the following orders", ((string)(null)), table21, "And ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Order Number",
                        "Tracking Number",
                        "Status"});
            table22.AddRow(new string[] {
                        "1",
                        "098765432109",
                        "1234",
                        "Received"});
            table22.AddRow(new string[] {
                        "2",
                        "098765432109",
                        "1234",
                        "Disposed"});
            table22.AddRow(new string[] {
                        "3",
                        "098765432109",
                        "1234",
                        "Returned"});
            table22.AddRow(new string[] {
                        "4",
                        "098765432109",
                        "1234",
                        "ReturnRequested"});
#line 157
 testRunner.When("I update orders as follows", ((string)(null)), table22, "When ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Order Number",
                        "Tracking Number",
                        "Status",
                        "Message Type",
                        "Error Code"});
            table23.AddRow(new string[] {
                        "1",
                        "098765432109",
                        "1234",
                        "Received",
                        "Error",
                        "OrderCannotBeUpdated"});
            table23.AddRow(new string[] {
                        "2",
                        "098765432109",
                        "1234",
                        "Disposed",
                        "Error",
                        "OrderCannotBeUpdated"});
            table23.AddRow(new string[] {
                        "3",
                        "098765432109",
                        "1234",
                        "Returned",
                        "Error",
                        "OrderCannotBeUpdated"});
            table23.AddRow(new string[] {
                        "4",
                        "098765432109",
                        "1234",
                        "ReturnRequested",
                        "Error",
                        "OrderCannotBeUpdated"});
#line 163
 testRunner.Then("the order view models should be as follows", ((string)(null)), table23, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update order in new status validate fields max length")]
        [NUnit.Framework.CategoryAttribute("updateorder")]
        public virtual void UpdateOrderInNewStatusValidateFieldsMaxLength()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update order in new status validate fields max length", new string[] {
                        "updateorder"});
#line 171
this.ScenarioSetup(scenarioInfo);
#line 172
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Shopper" +
                    "\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 173
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer",
                        "Order Number",
                        "Tracking Number",
                        "Status"});
            table24.AddRow(new string[] {
                        "1",
                        "amazon.com",
                        "",
                        "123456789012345",
                        "New"});
#line 174
 testRunner.And("I have the following orders", ((string)(null)), table24, "And ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Order Number",
                        "Tracking Number",
                        "Status"});
            table25.AddRow(new string[] {
                        "1",
                        "098765432109098765432109098765432109098765432109",
                        "123456789012345123456789012345123456789012345123456789012345",
                        "New"});
#line 177
 testRunner.When("I update order as follows", ((string)(null)), table25, "When ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Order Number",
                        "Tracking Number",
                        "Status",
                        "Message Type"});
            table26.AddRow(new string[] {
                        "1",
                        "098765432109098765432109098765432109098765432109",
                        "123456789012345123456789012345123456789012345123456789012345",
                        "New",
                        "Warning"});
#line 180
 testRunner.Then("the order view model should be as follows", ((string)(null)), table26, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Error Code"});
            table27.AddRow(new string[] {
                        "OrderNumber",
                        "OrderOrderNumberMaxLength"});
            table27.AddRow(new string[] {
                        "TrackingNumber",
                        "OrderTrackingNumberMaxLength"});
#line 183
 testRunner.And("the order view model should have the following errors", ((string)(null)), table27, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Remove order in new status should be possible by shopper")]
        [NUnit.Framework.CategoryAttribute("removeorder")]
        public virtual void RemoveOrderInNewStatusShouldBePossibleByShopper()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Remove order in new status should be possible by shopper", new string[] {
                        "removeorder"});
#line 189
this.ScenarioSetup(scenarioInfo);
#line 190
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Shopper" +
                    "\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 191
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status"});
            table28.AddRow(new string[] {
                        "1",
                        "amazon.com",
                        "",
                        "",
                        "",
                        "New"});
#line 192
 testRunner.And("I have the following orders", ((string)(null)), table28, "And ");
#line 195
 testRunner.When("I remove order with id \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer Url",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status",
                        "Message Type"});
            table29.AddRow(new string[] {
                        "1",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "Success"});
#line 196
 testRunner.Then("the order view model should be as follows", ((string)(null)), table29, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Remove order in new status should be possible by admin")]
        [NUnit.Framework.CategoryAttribute("removeorder")]
        public virtual void RemoveOrderInNewStatusShouldBePossibleByAdmin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Remove order in new status should be possible by admin", new string[] {
                        "removeorder"});
#line 201
this.ScenarioSetup(scenarioInfo);
#line 202
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Admin\' " +
                    "with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 203
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status"});
            table30.AddRow(new string[] {
                        "1",
                        "amazon.com",
                        "",
                        "",
                        "",
                        "New"});
#line 204
 testRunner.And("I have the following orders", ((string)(null)), table30, "And ");
#line 207
 testRunner.When("I remove order with id \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer Url",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status",
                        "Message Type"});
            table31.AddRow(new string[] {
                        "1",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "Success"});
#line 208
 testRunner.Then("the order view model should be as follows", ((string)(null)), table31, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Remove order in other status than new should not be possible")]
        [NUnit.Framework.CategoryAttribute("removeorder")]
        public virtual void RemoveOrderInOtherStatusThanNewShouldNotBePossible()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Remove order in other status than new should not be possible", new string[] {
                        "removeorder"});
#line 213
this.ScenarioSetup(scenarioInfo);
#line 214
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Shopper" +
                    "\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 215
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status"});
            table32.AddRow(new string[] {
                        "1",
                        "amazon.com",
                        "",
                        "",
                        "",
                        "Received"});
            table32.AddRow(new string[] {
                        "2",
                        "6pm.com",
                        "",
                        "",
                        "",
                        "Returned"});
            table32.AddRow(new string[] {
                        "3",
                        "apple.com",
                        "",
                        "",
                        "",
                        "ReturnRequested"});
            table32.AddRow(new string[] {
                        "4",
                        "zappos.com",
                        "",
                        "",
                        "",
                        "Disposed"});
#line 216
 testRunner.And("I have the following orders", ((string)(null)), table32, "And ");
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id"});
            table33.AddRow(new string[] {
                        "1"});
            table33.AddRow(new string[] {
                        "2"});
            table33.AddRow(new string[] {
                        "3"});
            table33.AddRow(new string[] {
                        "4"});
#line 222
 testRunner.When("I remove the following orders", ((string)(null)), table33, "When ");
#line hidden
            TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer Url",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status",
                        "Message Type",
                        "Error Code"});
            table34.AddRow(new string[] {
                        "1",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "Error",
                        "OrderCannotBeRemoved"});
            table34.AddRow(new string[] {
                        "2",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "Error",
                        "OrderCannotBeRemoved"});
            table34.AddRow(new string[] {
                        "3",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "Error",
                        "OrderCannotBeRemoved"});
            table34.AddRow(new string[] {
                        "4",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "Error",
                        "OrderCannotBeRemoved"});
#line 228
 testRunner.Then("the order view models should be as follows", ((string)(null)), table34, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Remove order that does not exist")]
        [NUnit.Framework.CategoryAttribute("removeorder")]
        public virtual void RemoveOrderThatDoesNotExist()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Remove order that does not exist", new string[] {
                        "removeorder"});
#line 236
this.ScenarioSetup(scenarioInfo);
#line 237
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Shopper" +
                    "\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 238
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status"});
            table35.AddRow(new string[] {
                        "1",
                        "amazon.com",
                        "",
                        "",
                        "",
                        "New"});
#line 239
 testRunner.And("I have the following orders", ((string)(null)), table35, "And ");
#line 242
 testRunner.When("I remove order with id \'2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer Url",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status",
                        "Message Type",
                        "Error Code"});
            table36.AddRow(new string[] {
                        "2",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "Error",
                        "OrderNotFoundForUser"});
#line 243
 testRunner.Then("the order view model should be as follows", ((string)(null)), table36, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Remove order should not be possible by operator")]
        [NUnit.Framework.CategoryAttribute("removeorder")]
        public virtual void RemoveOrderShouldNotBePossibleByOperator()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Remove order should not be possible by operator", new string[] {
                        "removeorder"});
#line 248
this.ScenarioSetup(scenarioInfo);
#line 249
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Operato" +
                    "r\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 250
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status"});
            table37.AddRow(new string[] {
                        "1",
                        "amazon.com",
                        "",
                        "",
                        "",
                        "New"});
#line 251
 testRunner.And("I have the following orders", ((string)(null)), table37, "And ");
#line 254
 testRunner.When("I remove order with id \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer Url",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status",
                        "Message Type",
                        "Error Code"});
            table38.AddRow(new string[] {
                        "1",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "Error",
                        "OrderCannotBeRemoved"});
#line 255
 testRunner.Then("the order view model should be as follows", ((string)(null)), table38, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Remove order should not be possible by consultant")]
        [NUnit.Framework.CategoryAttribute("removeorder")]
        public virtual void RemoveOrderShouldNotBePossibleByConsultant()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Remove order should not be possible by consultant", new string[] {
                        "removeorder"});
#line 260
this.ScenarioSetup(scenarioInfo);
#line 261
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Consult" +
                    "ant\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 262
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status"});
            table39.AddRow(new string[] {
                        "1",
                        "amazon.com",
                        "",
                        "",
                        "",
                        "New"});
#line 263
 testRunner.And("I have the following orders", ((string)(null)), table39, "And ");
#line 266
 testRunner.When("I remove order with id \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer Url",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status",
                        "Message Type",
                        "Error Code"});
            table40.AddRow(new string[] {
                        "1",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "Error",
                        "OrderCannotBeRemoved"});
#line 267
 testRunner.Then("the order view model should be as follows", ((string)(null)), table40, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Request for order return")]
        [NUnit.Framework.CategoryAttribute("requestorderreturn")]
        public virtual void RequestForOrderReturn()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Request for order return", new string[] {
                        "requestorderreturn"});
#line 272
this.ScenarioSetup(scenarioInfo);
#line 273
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Shopper" +
                    "\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 274
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status"});
            table41.AddRow(new string[] {
                        "1",
                        "amazon.com",
                        "",
                        "",
                        "",
                        "Received"});
#line 275
 testRunner.And("I have the following orders", ((string)(null)), table41, "And ");
#line hidden
            TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id"});
            table42.AddRow(new string[] {
                        "1"});
#line 278
 testRunner.When("I request for following orders return", ((string)(null)), table42, "When ");
#line hidden
            TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer Url",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status",
                        "Message Type"});
            table43.AddRow(new string[] {
                        "1",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "Success"});
#line 281
 testRunner.Then("the order view models should be as follows", ((string)(null)), table43, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
