// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.17929
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TdService.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Shopper Orders")]
    [NUnit.Framework.CategoryAttribute("orders")]
    public partial class ShopperOrdersFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ShopperOrders.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Shopper Orders", "In order to let operator know about incoming orders\r\nAs a shopper\r\nI want to be a" +
                    "ble to add new orders, remove them and update with tracking number and order num" +
                    "ber", ProgrammingLanguage.CSharp, new string[] {
                        "orders"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("View my recent orders")]
        [NUnit.Framework.CategoryAttribute("viewrecentorders")]
        public virtual void ViewMyRecentOrders()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("View my recent orders", new string[] {
                        "viewrecentorders"});
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Shopper" +
                    "\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer",
                        "Order Number",
                        "Tracking Number",
                        "Status"});
            table1.AddRow(new string[] {
                        "1",
                        "amazon.com",
                        "",
                        "773456789012345",
                        "New"});
            table1.AddRow(new string[] {
                        "2",
                        "6pm.com",
                        "123453453455",
                        "673456789012345",
                        "Received"});
            table1.AddRow(new string[] {
                        "3",
                        "zazzle.com",
                        "125675575445",
                        "344567895675664",
                        "Returned"});
            table1.AddRow(new string[] {
                        "4",
                        "yoox.com",
                        "455367456655",
                        "34567893442345",
                        "Disposed"});
            table1.AddRow(new string[] {
                        "5",
                        "zappos.com",
                        "234345454433",
                        "123456789012345",
                        "Received"});
            table1.AddRow(new string[] {
                        "6",
                        "zappos.com",
                        "453656457544",
                        "245763453445463",
                        "ReturnRequested"});
#line 11
 testRunner.And("I have the following orders", ((string)(null)), table1, "And ");
#line 19
 testRunner.When("I go to my recent orders tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer Url",
                        "Order Number",
                        "Tracking Number",
                        "Status",
                        "Can Be Modified",
                        "Can Be Removed",
                        "Can Be Requested For Return",
                        "Can Items Be Modified",
                        "Message Type"});
            table2.AddRow(new string[] {
                        "1",
                        "amazon.com",
                        "",
                        "773456789012345",
                        "New",
                        "True",
                        "True",
                        "False",
                        "True",
                        "Success"});
            table2.AddRow(new string[] {
                        "2",
                        "6pm.com",
                        "123453453455",
                        "673456789012345",
                        "Received",
                        "False",
                        "False",
                        "True",
                        "False",
                        "Success"});
            table2.AddRow(new string[] {
                        "5",
                        "zappos.com",
                        "234345454433",
                        "123456789012345",
                        "Received",
                        "False",
                        "False",
                        "True",
                        "False",
                        "Success"});
            table2.AddRow(new string[] {
                        "6",
                        "zappos.com",
                        "453656457544",
                        "245763453445463",
                        "ReturnRequested",
                        "False",
                        "False",
                        "False",
                        "False",
                        "Success"});
#line 20
 testRunner.Then("the order view models should be as follows", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add new order")]
        [NUnit.Framework.CategoryAttribute("addorder")]
        public virtual void AddNewOrder()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add new order", new string[] {
                        "addorder"});
#line 28
this.ScenarioSetup(scenarioInfo);
#line 29
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Shopper" +
                    "\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 30
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.When("I set retailer url as \'amazon.com\' and press add order button on shopper dashboar" +
                    "d page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer Url",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status",
                        "Can Be Modified",
                        "Can Be Removed",
                        "Can Be Requested For Return",
                        "Can Items Be Modified",
                        "Message Type"});
            table3.AddRow(new string[] {
                        "1",
                        "amazon.com",
                        "",
                        "",
                        "",
                        "New",
                        "True",
                        "True",
                        "False",
                        "True",
                        "Success"});
#line 32
 testRunner.Then("the order view model should be as follows", ((string)(null)), table3, "Then ");
#line 35
 testRunner.And("the order view model should have Created Date that is earlier than UTC Now", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add new order reusing existent retailer instead of creating new one")]
        [NUnit.Framework.CategoryAttribute("addorder")]
        public virtual void AddNewOrderReusingExistentRetailerInsteadOfCreatingNewOne()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add new order reusing existent retailer instead of creating new one", new string[] {
                        "addorder"});
#line 38
this.ScenarioSetup(scenarioInfo);
#line 39
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Shopper" +
                    "\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 40
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer",
                        "Order Number",
                        "Tracking Number",
                        "Status"});
            table4.AddRow(new string[] {
                        "1",
                        "amazon.com",
                        "",
                        "773456789012345",
                        "New"});
#line 41
 testRunner.And("I have the following orders", ((string)(null)), table4, "And ");
#line 44
 testRunner.When("I set retailer url as \'amazon.com\' and press add order button on shopper dashboar" +
                    "d page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer Url",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status",
                        "Can Be Modified",
                        "Can Be Removed",
                        "Can Be Requested For Return",
                        "Can Items Be Modified",
                        "Message Type"});
            table5.AddRow(new string[] {
                        "2",
                        "amazon.com",
                        "",
                        "",
                        "",
                        "New",
                        "True",
                        "True",
                        "False",
                        "True",
                        "Success"});
#line 45
 testRunner.Then("the order view model should be as follows", ((string)(null)), table5, "Then ");
#line 48
 testRunner.And("there must be only one db record with \'amazon.com\' retailer url", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add new order validate retailer url is required")]
        [NUnit.Framework.CategoryAttribute("addorder")]
        public virtual void AddNewOrderValidateRetailerUrlIsRequired()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add new order validate retailer url is required", new string[] {
                        "addorder"});
#line 51
this.ScenarioSetup(scenarioInfo);
#line 52
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Shopper" +
                    "\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 53
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 54
 testRunner.When("I set retailer url as \'\' and press add order button on shopper dashboard page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer Url",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status",
                        "Can Be Modified",
                        "Can Be Removed",
                        "Can Be Requested For Return",
                        "Can Items Be Modified",
                        "Message Type"});
            table6.AddRow(new string[] {
                        "0",
                        "",
                        "",
                        "",
                        "",
                        "New",
                        "False",
                        "False",
                        "False",
                        "False",
                        "Warning"});
#line 55
 testRunner.Then("the order view model should be as follows", ((string)(null)), table6, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Error Code"});
            table7.AddRow(new string[] {
                        "RetailerUrl",
                        "OrderRetailerRequired"});
#line 58
 testRunner.And("the order view model should have the following errors", ((string)(null)), table7, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add new order validate retailer max length")]
        [NUnit.Framework.CategoryAttribute("addorder")]
        public virtual void AddNewOrderValidateRetailerMaxLength()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add new order validate retailer max length", new string[] {
                        "addorder"});
#line 63
this.ScenarioSetup(scenarioInfo);
#line 64
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Shopper" +
                    "\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 65
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 66
 testRunner.When(@"I set retailer url as 'this is the very long an unusual retailer url that is not actually a url but a long text that exceeds the maximum allowed length for url addresses this is the very long an unusual retailer url that is not actually a url but a long text that exceeds the maximum allowed length for url addresses' and press add order button on shopper dashboard page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer Url",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status",
                        "Can Be Modified",
                        "Can Be Removed",
                        "Can Be Requested For Return",
                        "Can Items Be Modified",
                        "Message Type"});
            table8.AddRow(new string[] {
                        "0",
                        @"this is the very long an unusual retailer url that is not actually a url but a long text that exceeds the maximum allowed length for url addresses this is the very long an unusual retailer url that is not actually a url but a long text that exceeds the maximum allowed length for url addresses",
                        "",
                        "",
                        "",
                        "New",
                        "False",
                        "False",
                        "False",
                        "False",
                        "Warning"});
#line 67
 testRunner.Then("the order view model should be as follows", ((string)(null)), table8, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Error Code"});
            table9.AddRow(new string[] {
                        "RetailerUrl",
                        "RetailerUrlMaxLength"});
#line 70
 testRunner.And("the order view model should have the following errors", ((string)(null)), table9, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update order in new status")]
        [NUnit.Framework.CategoryAttribute("updateorder")]
        public virtual void UpdateOrderInNewStatus()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update order in new status", new string[] {
                        "updateorder"});
#line 75
this.ScenarioSetup(scenarioInfo);
#line 76
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Shopper" +
                    "\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 77
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer",
                        "Order Number",
                        "Tracking Number",
                        "Status"});
            table10.AddRow(new string[] {
                        "1",
                        "amazon.com",
                        "",
                        "123456789012345",
                        "New"});
#line 78
 testRunner.And("I have the following orders", ((string)(null)), table10, "And ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Order Number",
                        "Tracking Number",
                        "Status"});
            table11.AddRow(new string[] {
                        "1",
                        "098765432109",
                        "1234",
                        "New"});
#line 81
 testRunner.When("I update order as follows", ((string)(null)), table11, "When ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Order Number",
                        "Tracking Number",
                        "Status",
                        "Message Type"});
            table12.AddRow(new string[] {
                        "1",
                        "098765432109",
                        "1234",
                        "New",
                        "Success"});
#line 84
 testRunner.Then("the order view model should be as follows", ((string)(null)), table12, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Remove order in new status")]
        [NUnit.Framework.CategoryAttribute("removeorder")]
        public virtual void RemoveOrderInNewStatus()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Remove order in new status", new string[] {
                        "removeorder"});
#line 89
this.ScenarioSetup(scenarioInfo);
#line 90
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Shopper" +
                    "\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 91
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status"});
            table13.AddRow(new string[] {
                        "1",
                        "amazon.com",
                        "",
                        "",
                        "",
                        "New"});
#line 92
 testRunner.And("I have the following orders", ((string)(null)), table13, "And ");
#line 95
 testRunner.When("I remove order with id \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer Url",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status",
                        "Message Type"});
            table14.AddRow(new string[] {
                        "1",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "Success"});
#line 96
 testRunner.Then("the order view model should be as follows", ((string)(null)), table14, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Remove order in other status than new should not be possible")]
        [NUnit.Framework.CategoryAttribute("removeorder")]
        public virtual void RemoveOrderInOtherStatusThanNewShouldNotBePossible()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Remove order in other status than new should not be possible", new string[] {
                        "removeorder"});
#line 101
this.ScenarioSetup(scenarioInfo);
#line 102
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Shopper" +
                    "\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 103
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status"});
            table15.AddRow(new string[] {
                        "1",
                        "amazon.com",
                        "",
                        "",
                        "",
                        "Received"});
            table15.AddRow(new string[] {
                        "2",
                        "6pm.com",
                        "",
                        "",
                        "",
                        "Returned"});
            table15.AddRow(new string[] {
                        "3",
                        "apple.com",
                        "",
                        "",
                        "",
                        "ReturnRequested"});
            table15.AddRow(new string[] {
                        "4",
                        "zappos.com",
                        "",
                        "",
                        "",
                        "Disposed"});
#line 104
 testRunner.And("I have the following orders", ((string)(null)), table15, "And ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id"});
            table16.AddRow(new string[] {
                        "1"});
            table16.AddRow(new string[] {
                        "2"});
            table16.AddRow(new string[] {
                        "3"});
            table16.AddRow(new string[] {
                        "4"});
#line 110
 testRunner.When("I remove the following orders", ((string)(null)), table16, "When ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer Url",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status",
                        "Message Type",
                        "Error Code"});
            table17.AddRow(new string[] {
                        "1",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "Error",
                        "OrderCannotBeRemoved"});
            table17.AddRow(new string[] {
                        "2",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "Error",
                        "OrderCannotBeRemoved"});
            table17.AddRow(new string[] {
                        "3",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "Error",
                        "OrderCannotBeRemoved"});
            table17.AddRow(new string[] {
                        "4",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "Error",
                        "OrderCannotBeRemoved"});
#line 116
 testRunner.Then("the order view models should be as follows", ((string)(null)), table17, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Remove order that does not exist")]
        [NUnit.Framework.CategoryAttribute("removeorder")]
        public virtual void RemoveOrderThatDoesNotExist()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Remove order that does not exist", new string[] {
                        "removeorder"});
#line 124
this.ScenarioSetup(scenarioInfo);
#line 125
 testRunner.Given("there is \'v.hatalski@gmail.com\' account with \'ruinruin\' password in role \'Shopper" +
                    "\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 126
 testRunner.And("I am authenticated as \'v.hatalski@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status"});
            table18.AddRow(new string[] {
                        "1",
                        "amazon.com",
                        "",
                        "",
                        "",
                        "New"});
#line 127
 testRunner.And("I have the following orders", ((string)(null)), table18, "And ");
#line 130
 testRunner.When("I remove order with id \'2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Retailer Url",
                        "Order Number",
                        "Tracking Number",
                        "Received Date",
                        "Status",
                        "Message Type",
                        "Error Code"});
            table19.AddRow(new string[] {
                        "2",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "Error",
                        "OrderNotBelongToUser"});
#line 131
 testRunner.Then("the order view model should be as follows", ((string)(null)), table19, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
