// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.17929
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TdService.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Sign In")]
    [NUnit.Framework.CategoryAttribute("signin")]
    public partial class SignInFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SignIn.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Sign In", "In order to start using service\r\nAs a shopper\r\nI want to be able to sign in with " +
                    "my credentials", ProgrammingLanguage.CSharp, new string[] {
                        "signin"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Sign in shopper")]
        [NUnit.Framework.CategoryAttribute("shopper")]
        public virtual void SignInShopper()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sign in shopper", new string[] {
                        "shopper"});
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("I have not been authenticated yet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.And("The \'vhatalski@naviam.com\' account already exists", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.And("I am in \'Shopper\' role", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "Remember Me"});
            table1.AddRow(new string[] {
                        "vhatalski@naviam.com",
                        "ruinruin",
                        "false"});
#line 12
 testRunner.When("I fill sign in form with the following data", ((string)(null)), table1, "When ");
#line 15
 testRunner.Then("I should be redirected to controller \'Member\' and action \'Dashboard\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Shopper invalid credentials")]
        [NUnit.Framework.CategoryAttribute("shopper")]
        public virtual void ShopperInvalidCredentials()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Shopper invalid credentials", new string[] {
                        "shopper"});
#line 18
this.ScenarioSetup(scenarioInfo);
#line 19
 testRunner.Given("I have not been authenticated yet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 20
 testRunner.And("The \'vhatalski@naviam.com\' account already exists", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
 testRunner.And("I am in \'Shopper\' role", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "Remember Me"});
            table2.AddRow(new string[] {
                        "vhatalski@naviam.com",
                        "ruinruin3",
                        "false"});
#line 22
 testRunner.When("I fill sign in form with the following data", ((string)(null)), table2, "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "Remember Me",
                        "Message Type",
                        "Error Code"});
            table3.AddRow(new string[] {
                        "vhatalski@naviam.com",
                        "",
                        "false",
                        "Error",
                        "UserNotValid"});
#line 25
 testRunner.Then("the signin result should be as follows", ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Shopper validate required fields")]
        [NUnit.Framework.CategoryAttribute("shopper")]
        public virtual void ShopperValidateRequiredFields()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Shopper validate required fields", new string[] {
                        "shopper"});
#line 30
this.ScenarioSetup(scenarioInfo);
#line 31
 testRunner.Given("I have not been authenticated yet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 32
 testRunner.And("The \'vhatalski@naviam.com\' account already exists", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
 testRunner.And("I am in \'Shopper\' role", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "Remember Me"});
            table4.AddRow(new string[] {
                        "",
                        "",
                        "false"});
#line 34
 testRunner.When("I fill sign in form with the following data", ((string)(null)), table4, "When ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "Remember Me",
                        "Message Type"});
            table5.AddRow(new string[] {
                        "",
                        "",
                        "false",
                        "Warning"});
#line 37
 testRunner.Then("the signin result should be as follows", ((string)(null)), table5, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Error Code"});
            table6.AddRow(new string[] {
                        "Email",
                        "UserEmailRequired"});
            table6.AddRow(new string[] {
                        "Password",
                        "UserPasswordRequired"});
#line 40
 testRunner.And("the signin view model should have following errors", ((string)(null)), table6, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Sign in operator")]
        [NUnit.Framework.CategoryAttribute("operator")]
        public virtual void SignInOperator()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sign in operator", new string[] {
                        "operator"});
#line 46
this.ScenarioSetup(scenarioInfo);
#line 47
 testRunner.Given("I have not been authenticated yet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 48
 testRunner.And("The \'vhatalski@naviam.com\' account already exists", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
 testRunner.And("I am in \'Operator\' role", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "Remember Me"});
            table7.AddRow(new string[] {
                        "vhatalski@naviam.com",
                        "ruinruin",
                        "false"});
#line 50
 testRunner.When("I fill sign in form with the following data", ((string)(null)), table7, "When ");
#line 53
 testRunner.Then("I should be redirected to controller \'Admin\' and action \'Dashboard\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Sign in conslutant")]
        [NUnit.Framework.CategoryAttribute("consultant")]
        public virtual void SignInConslutant()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sign in conslutant", new string[] {
                        "consultant"});
#line 56
this.ScenarioSetup(scenarioInfo);
#line 57
 testRunner.Given("I have not been authenticated yet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 58
 testRunner.And("The \'vhatalski@naviam.com\' account already exists", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
 testRunner.And("I am in \'Consultant\' role", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "Remember Me"});
            table8.AddRow(new string[] {
                        "vhatalski@naviam.com",
                        "ruinruin",
                        "false"});
#line 60
 testRunner.When("I fill sign in form with the following data", ((string)(null)), table8, "When ");
#line 63
 testRunner.Then("I should be redirected to controller \'Admin\' and action \'Dashboard\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Sign in admin")]
        [NUnit.Framework.CategoryAttribute("admin")]
        public virtual void SignInAdmin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sign in admin", new string[] {
                        "admin"});
#line 66
this.ScenarioSetup(scenarioInfo);
#line 67
 testRunner.Given("I have not been authenticated yet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 68
 testRunner.And("The \'vhatalski@naviam.com\' account already exists", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 69
 testRunner.And("I am in \'Admin\' role", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "Remember Me"});
            table9.AddRow(new string[] {
                        "vhatalski@naviam.com",
                        "ruinruin",
                        "false"});
#line 70
 testRunner.When("I fill sign in form with the following data", ((string)(null)), table9, "When ");
#line 73
 testRunner.Then("I should be redirected to controller \'Admin\' and action \'Dashboard\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
