//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TdService.Domain.Repositories
{
	using Domain;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IAddressRepository 
	{
		IEnumerable<Address> GetDeliveryAddresses(string username);

		Address GetWarehouseAddress(string username);

		void AddDeliveryAddress(string username, Address address);

		void UpdateDeliveryAddress(Address address);

		void RemoveDeliveryAddress(int addressId);

		Address GetDeliveryAddressDetails(int addressId);

	}
}

