//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TdService.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class NotificationRules
	{
		public virtual bool NotifyOrderStatusChanged
		{
			get;
			set;
		}

		public virtual bool NotifyParcelStatusChanged
		{
			get;
			set;
		}

	}
}

