//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TdService.Model.Orders
{
    public enum OrderStatus : int
    {
        WaitingArrival = 0,
        Arrived = 1,
        Processed = 2,
    }
}