//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TdService.Domain.Repositories
{
	using Domain;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IOrderRepository 
	{
		void AddOrder(Order order, string userId);

		void RemoveOrder(int orderId);

		void UpdateOrder(Order order);

		/// <param name="pageSize">The number of items to show on a single page.</param>
		IEnumerable<Order> GetAllOrders(object sortDirection, string sortExpression, string filterExpression, int pageSize = 20);

		IEnumerable<Order> GetUserOrders(string username, object sortDirection, string sortExpression, string filterExpression, int pageSize = 20);

		Order GetOrderDetails(int orderId);

		void RequestPhotos(int orderId);

		void AddPhotoes(int orderId, IEnumerable<Picture> picture);

		void UpdateOrderStatus(int orderId, OrderStatus newStatus);

		void UpdateArrivalDate(int orderId, DateTime arrivalDate);

		void UpdateOrderWeight(int orderId, Weight weight);

	}
}

