//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TdService.Domain.Repositories
{
	using Domain;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IItemRepository 
	{
		IEnumerable<Item> GetOrderItems(int orderId);

		void AddItemToOrder(int orderId, Item item);

		void UpdateItem(Item item);

		void RemoveItem(int itemId);

		void RequestItemReturn(int itemId);

	}
}

