//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TdService.Domain.Repositories
{
	using Domain;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IParcelRepository 
	{
		void AddOrdersToParcel(int parcelId, IEnumerable<Order> orders);

		void RemoveParcel(int parcelId);

		IEnumerable<Parcel> GetUserParcels(string username, object sortDirection, string sortExpression, string filterExpression, int pageSize);

		IEnumerable<Parcel> GetAllParcels(object sortDirection, string sortExpression, string filterExpression, int pageSize = 20);

		Parcel GetParcelDetails(int parcelId);

		void UpdateParcel(Parcel parcel);

		void UpdateParcelStatus(int parcelId, ParcelStatus newStatus);

		/// <summary>
		/// Adds new parcel and returns parcel id
		/// </summary>
		int AddParcel(string username, Parcel parcel);

	}
}

