//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TdService.Domain
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Address
	{
		public virtual string AddressName
		{
			get;
			set;
		}

		public virtual string RecipientFirstName
		{
			get;
			set;
		}

		public virtual int Zip
		{
			get;
			set;
		}

		public virtual string Country
		{
			get;
			set;
		}

		public virtual string Region
		{
			get;
			set;
		}

		public virtual string City
		{
			get;
			set;
		}

		public virtual string Address1
		{
			get;
			set;
		}

		public virtual string Address2
		{
			get;
			set;
		}

		public virtual string Address3
		{
			get;
			set;
		}

		public virtual string Phone
		{
			get;
			set;
		}

		public virtual string RecipientLastName
		{
			get;
			set;
		}

		public virtual string State
		{
			get;
			set;
		}

		public virtual int Id
		{
			get;
			set;
		}

		public virtual bool IsStorehouse
		{
			get;
			set;
		}

	}
}

