//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TdService.Domain
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// Post service and method which will be used to send parcel to the user's delivery address
	/// </summary>
	public enum DispatchMethod : int
	{
		ExpressMail,
		PriorityMail,
	}
}
