//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TdService.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessRules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessRules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TdService.Resources.BusinessRules", typeof(BusinessRules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The 1st line of an Address is required..
        /// </summary>
        public static string Address_AddressLine1Required {
            get {
                return ResourceManager.GetString("Address_AddressLine1Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An address must have a city..
        /// </summary>
        public static string Address_CityRequired {
            get {
                return ResourceManager.GetString("Address_CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An address must have a country..
        /// </summary>
        public static string Address_CountryRequired {
            get {
                return ResourceManager.GetString("Address_CountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An address must have a zip code..
        /// </summary>
        public static string Address_ZipCodeRequired {
            get {
                return ResourceManager.GetString("Address_ZipCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A delivery address must have a name..
        /// </summary>
        public static string DeliveryAddress_AddressNameRequired {
            get {
                return ResourceManager.GetString("DeliveryAddress_AddressNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A delivery address must contain your first name..
        /// </summary>
        public static string DeliveryAddress_FirstNameRequired {
            get {
                return ResourceManager.GetString("DeliveryAddress_FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A delivery address must contain your last name..
        /// </summary>
        public static string DeliveryAddress_LastNameRequired {
            get {
                return ResourceManager.GetString("DeliveryAddress_LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is a required field. It is used to generate your U.S. address..
        /// </summary>
        public static string Profile_FirstNameRequired {
            get {
                return ResourceManager.GetString("Profile_FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is a required field. It is used to generate your U.S. address..
        /// </summary>
        public static string Profile_LastNameRequired {
            get {
                return ResourceManager.GetString("Profile_LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An user must have an email..
        /// </summary>
        public static string User_EmailRequired {
            get {
                return ResourceManager.GetString("User_EmailRequired", resourceCulture);
            }
        }
    }
}
