//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TdService.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessRules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessRules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TdService.Resources.BusinessRules", typeof(BusinessRules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The 1st line of an Address is required..
        /// </summary>
        public static string Address_AddressLine1Required {
            get {
                return ResourceManager.GetString("Address_AddressLine1Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An address must have a city..
        /// </summary>
        public static string Address_CityRequired {
            get {
                return ResourceManager.GetString("Address_CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An address must have a country..
        /// </summary>
        public static string Address_CountryRequired {
            get {
                return ResourceManager.GetString("Address_CountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An address must have a zip code..
        /// </summary>
        public static string Address_ZipCodeRequired {
            get {
                return ResourceManager.GetString("Address_ZipCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courier name must be a string with a maximum length of 64..
        /// </summary>
        public static string Courier_NameMaxLength {
            get {
                return ResourceManager.GetString("Courier_NameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A courier must have a name..
        /// </summary>
        public static string Courier_NameRequired {
            get {
                return ResourceManager.GetString("Courier_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A delivery address must have a name..
        /// </summary>
        public static string DeliveryAddress_AddressNameRequired {
            get {
                return ResourceManager.GetString("DeliveryAddress_AddressNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A delivery address must contain your first name..
        /// </summary>
        public static string DeliveryAddress_FirstNameRequired {
            get {
                return ResourceManager.GetString("DeliveryAddress_FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A delivery address must contain your last name..
        /// </summary>
        public static string DeliveryAddress_LastNameRequired {
            get {
                return ResourceManager.GetString("DeliveryAddress_LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order must have a created date..
        /// </summary>
        public static string Order_CreatedDateRequired {
            get {
                return ResourceManager.GetString("Order_CreatedDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order number must be a string with a maximum length of 64..
        /// </summary>
        public static string Order_OrderNumberLength {
            get {
                return ResourceManager.GetString("Order_OrderNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order in Received status must have a received date..
        /// </summary>
        public static string Order_ReceivedDateRequired {
            get {
                return ResourceManager.GetString("Order_ReceivedDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order must have a retailer..
        /// </summary>
        public static string Order_RetailerRequired {
            get {
                return ResourceManager.GetString("Order_RetailerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order extended status must be a string with a maximum length of 64..
        /// </summary>
        public static string Order_StatusExtendedLength {
            get {
                return ResourceManager.GetString("Order_StatusExtendedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking number must be a string with a maximum length of 64..
        /// </summary>
        public static string Order_TrackingNumberLength {
            get {
                return ResourceManager.GetString("Order_TrackingNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order in Received status must have a weight..
        /// </summary>
        public static string Order_WeightRequired {
            get {
                return ResourceManager.GetString("Order_WeightRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package name must be a string with a maximum length of 64..
        /// </summary>
        public static string Package_NameLength {
            get {
                return ResourceManager.GetString("Package_NameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A package must have a name..
        /// </summary>
        public static string Package_NameRequired {
            get {
                return ResourceManager.GetString("Package_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name must be a string with a maximum length of 64..
        /// </summary>
        public static string Profile_FirstNameLength {
            get {
                return ResourceManager.GetString("Profile_FirstNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is a required field..
        /// </summary>
        public static string Profile_FirstNameRequired {
            get {
                return ResourceManager.GetString("Profile_FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name must be a string with a maximum length of 64..
        /// </summary>
        public static string Profile_LastNameLength {
            get {
                return ResourceManager.GetString("Profile_LastNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is a required field..
        /// </summary>
        public static string Profile_LastNameRequired {
            get {
                return ResourceManager.GetString("Profile_LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retailer category must be a string with a maximum length of 64..
        /// </summary>
        public static string Retailer_CategoryLength {
            get {
                return ResourceManager.GetString("Retailer_CategoryLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A retailer must have a category..
        /// </summary>
        public static string Retailer_CategoryRequired {
            get {
                return ResourceManager.GetString("Retailer_CategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retailer description must be a string with a maximum length of 1024..
        /// </summary>
        public static string Retailer_DescriptionLength {
            get {
                return ResourceManager.GetString("Retailer_DescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retailer name must be a string with a maximum length of 64..
        /// </summary>
        public static string Retailer_NameLength {
            get {
                return ResourceManager.GetString("Retailer_NameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A retailer must have a name..
        /// </summary>
        public static string Retailer_NameRequired {
            get {
                return ResourceManager.GetString("Retailer_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retailer url must be a string with a maximum length of 256..
        /// </summary>
        public static string Retailer_UrlLength {
            get {
                return ResourceManager.GetString("Retailer_UrlLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A retailer must have a url..
        /// </summary>
        public static string Retailer_UrlRequired {
            get {
                return ResourceManager.GetString("Retailer_UrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be a string with a maximum length of 64..
        /// </summary>
        public static string Role_DescriptionLength {
            get {
                return ResourceManager.GetString("Role_DescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be a string with a maximum length of 64..
        /// </summary>
        public static string Role_NameLength {
            get {
                return ResourceManager.GetString("Role_NameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A role must have a name..
        /// </summary>
        public static string Role_NameRequired {
            get {
                return ResourceManager.GetString("Role_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user already exists..
        /// </summary>
        public static string User_EmailExists {
            get {
                return ResourceManager.GetString("User_EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must be a string with a maximum length of 256..
        /// </summary>
        public static string User_EmailLength {
            get {
                return ResourceManager.GetString("User_EmailLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An user must have an email..
        /// </summary>
        public static string User_EmailRequired {
            get {
                return ResourceManager.GetString("User_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be a string with a maximum length of 64..
        /// </summary>
        public static string User_PasswordLength {
            get {
                return ResourceManager.GetString("User_PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be a string with a minimum length of 7..
        /// </summary>
        public static string User_PasswordMinLength {
            get {
                return ResourceManager.GetString("User_PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An user must have a password..
        /// </summary>
        public static string User_PasswordRequired {
            get {
                return ResourceManager.GetString("User_PasswordRequired", resourceCulture);
            }
        }
    }
}
