//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TdService.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TdService.Resources.EmailResources", typeof(EmailResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Email confirmation&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;background-color: #E9E9E9; margin: 8px; padding: 0; font-size: 12px&quot;&gt;
        ///    &lt;center&gt;
        ///    &lt;table style=&quot;width: 600px; border: none; font-size: 100%; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; font-family: &apos;Helvetica Neue&apos;, Helvetica, Arial, sans-serif;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;background: url(&apos;http://shopanyw [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailActivationBody {
            get {
                return ResourceManager.GetString("EmailActivationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noreply@shopanyware.com.
        /// </summary>
        public static string EmailActivationFrom {
            get {
                return ResourceManager.GetString("EmailActivationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address confirmation.
        /// </summary>
        public static string EmailActivationSubject {
            get {
                return ResourceManager.GetString("EmailActivationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Email confirmation&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;background-color: #E9E9E9; margin: 8px; padding: 0; font-size: 12px&quot;&gt;
        ///    &lt;center&gt;
        ///    &lt;table style=&quot;width: 600px; border: none; font-size: 100%; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; font-family: &apos;Helvetica Neue&apos;, Helvetica, Arial, sans-serif;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;background: url(&apos;top.png&apos;) no-re [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrderReceivedEmailBody {
            get {
                return ResourceManager.GetString("OrderReceivedEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has been received!.
        /// </summary>
        public static string OrderReceivedEmailSubject {
            get {
                return ResourceManager.GetString("OrderReceivedEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Email confirmation&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;background-color: #E9E9E9; margin: 8px; padding: 0; font-size: 12px&quot;&gt;
        ///    &lt;center&gt;
        ///    &lt;table style=&quot;width: 600px; border: none; font-size: 100%; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; font-family: &apos;Helvetica Neue&apos;, Helvetica, Arial, sans-serif;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;background: url(&apos;top.png&apos;) no-re [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PackageStatusChangedBody {
            get {
                return ResourceManager.GetString("PackageStatusChangedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package status was changed.
        /// </summary>
        public static string PackageStatusChangedSubject {
            get {
                return ResourceManager.GetString("PackageStatusChangedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To reset your password on ShopAnyWare.com please follow instructions on this link: &lt;a href=&quot;{0}account/NewPassword?passwordkey={1}&quot;&gt;{0}account/NewPassword?passwordkey={1}&lt;/a&gt;.
        /// </summary>
        public static string ResetPasswordBody {
            get {
                return ResourceManager.GetString("ResetPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password recovery for ShopAnyWare.com.
        /// </summary>
        public static string ResetPasswordSubject {
            get {
                return ResourceManager.GetString("ResetPasswordSubject", resourceCulture);
            }
        }
    }
}
