// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18010
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TdService.ShopAnyWare.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Sign Up")]
    [NUnit.Framework.CategoryAttribute("signup")]
    public partial class SignUpFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SignUp.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Sign Up", "In order to start using ShopAnyWare service\r\nAs an anonymous user\r\nI want to be a" +
                    "ble to register as a shopper and activate my personal account", ProgrammingLanguage.CSharp, new string[] {
                        "signup"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Shoppers sign up")]
        public virtual void ShoppersSignUp()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Shoppers sign up", ((string[])(null)));
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("I have not been authenticated yet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "Password Confirm",
                        "First Name",
                        "Last Name"});
            table1.AddRow(new string[] {
                        "hautama@tut.by",
                        "ruinruin",
                        "ruinruin",
                        "Vitali",
                        "Hatalski"});
#line 9
 testRunner.When("I fill sign up form with the following data", ((string)(null)), table1, "When ");
#line 12
 testRunner.Then("activation code should be generated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 13
 testRunner.And("email with activation code should be sent to registration email address", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.And("I should be redirected to controller \'Member\' and action \'Welcome\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Account already exists")]
        public virtual void AccountAlreadyExists()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Account already exists", ((string[])(null)));
#line 16
this.ScenarioSetup(scenarioInfo);
#line 17
 testRunner.Given("there is \'vhatalski@naviam.com\' account with \'ruinruin\' password in role \'Shopper" +
                    "\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 18
 testRunner.And("I have not been authenticated yet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "Password Confirm",
                        "First Name",
                        "Last Name"});
            table2.AddRow(new string[] {
                        "vhatalski@naviam.com",
                        "ruinruin",
                        "ruinruin",
                        "Vitali",
                        "Hatalski"});
#line 19
 testRunner.When("I fill sign up form with the following data", ((string)(null)), table2, "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name",
                        "Message Type"});
            table3.AddRow(new string[] {
                        "vhatalski@naviam.com",
                        "Vitali",
                        "Hatalski",
                        "Warning"});
#line 22
 testRunner.Then("I should have the result as follows", ((string)(null)), table3, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Error Code"});
            table4.AddRow(new string[] {
                        "Email",
                        "UserEmailExists"});
#line 25
 testRunner.And("the signup view model should have following errors", ((string)(null)), table4, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify email existence when it should exist")]
        public virtual void VerifyEmailExistenceWhenItShouldExist()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify email existence when it should exist", ((string[])(null)));
#line 29
this.ScenarioSetup(scenarioInfo);
#line 30
 testRunner.Given("there is \'vhatalski@naviam.com\' account with \'ruinruin\' password in role \'Shopper" +
                    "\' with fullname \'Vitali\' and \'Hatalski\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 31
 testRunner.And("I have not been authenticated yet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
 testRunner.When("I enter email \'vhatalski@naviam.com\' to verify existence", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "EmailExists",
                        "Message Type"});
            table5.AddRow(new string[] {
                        "True",
                        "Warning"});
#line 33
 testRunner.Then("the verify email view model should be as follows", ((string)(null)), table5, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify email existence when it should not exist")]
        public virtual void VerifyEmailExistenceWhenItShouldNotExist()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify email existence when it should not exist", ((string[])(null)));
#line 37
this.ScenarioSetup(scenarioInfo);
#line 38
 testRunner.Given("I have not been authenticated yet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 39
 testRunner.When("I enter email \'nosuchmail@naviam.com\' to verify existence", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "EmailExists",
                        "Message Type"});
            table6.AddRow(new string[] {
                        "False",
                        "Success"});
#line 40
 testRunner.Then("the verify email view model should be as follows", ((string)(null)), table6, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Email and password are required")]
        public virtual void EmailAndPasswordAreRequired()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Email and password are required", ((string[])(null)));
#line 44
this.ScenarioSetup(scenarioInfo);
#line 45
 testRunner.Given("I have not been authenticated yet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "Password Confirm",
                        "First Name",
                        "Last Name"});
            table7.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "Vitali",
                        "Hatalski"});
#line 46
 testRunner.When("I fill sign up form with the following data", ((string)(null)), table7, "When ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name",
                        "Message Type"});
            table8.AddRow(new string[] {
                        "",
                        "Vitali",
                        "Hatalski",
                        "Warning"});
#line 49
 testRunner.Then("I should have the result as follows", ((string)(null)), table8, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Error Code",
                        "Rule"});
            table9.AddRow(new string[] {
                        "Password",
                        "UserPasswordRequired",
                        ""});
            table9.AddRow(new string[] {
                        "Email",
                        "UserEmailRequired",
                        ""});
            table9.AddRow(new string[] {
                        "PasswordConfirm",
                        "UserPasswordConfirmRequired",
                        ""});
#line 52
 testRunner.And("the signup view model should have following errors", ((string)(null)), table9, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("First and Last names are required")]
        public virtual void FirstAndLastNamesAreRequired()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("First and Last names are required", ((string[])(null)));
#line 58
this.ScenarioSetup(scenarioInfo);
#line 59
 testRunner.Given("I have not been authenticated yet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "Password Confirm",
                        "First Name",
                        "Last Name"});
            table10.AddRow(new string[] {
                        "hautama@tut.by",
                        "ruinruin",
                        "ruinruin",
                        "",
                        ""});
#line 60
 testRunner.When("I fill sign up form with the following data", ((string)(null)), table10, "When ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name",
                        "Message Type"});
            table11.AddRow(new string[] {
                        "hautama@tut.by",
                        "",
                        "",
                        "Warning"});
#line 63
 testRunner.Then("I should have the result as follows", ((string)(null)), table11, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Error Code",
                        "Rule"});
            table12.AddRow(new string[] {
                        "FirstName",
                        "ProfileFirstNameRequired",
                        ""});
            table12.AddRow(new string[] {
                        "LastName",
                        "ProfileLastNameRequired",
                        ""});
#line 66
 testRunner.And("the signup view model should have following errors", ((string)(null)), table12, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("First and Last names should be less than 21 chars")]
        public virtual void FirstAndLastNamesShouldBeLessThan21Chars()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("First and Last names should be less than 21 chars", ((string[])(null)));
#line 71
this.ScenarioSetup(scenarioInfo);
#line 72
 testRunner.Given("I have not been authenticated yet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "Password Confirm",
                        "First Name",
                        "Last Name"});
            table13.AddRow(new string[] {
                        "hautama@tut.by",
                        "ruinruin",
                        "ruinruin",
                        "First name longer than 21 chars",
                        "Last name longer than 21 chars"});
#line 73
 testRunner.When("I fill sign up form with the following data", ((string)(null)), table13, "When ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name",
                        "Message Type"});
            table14.AddRow(new string[] {
                        "hautama@tut.by",
                        "First name longer than 21 chars",
                        "Last name longer than 21 chars",
                        "Warning"});
#line 76
 testRunner.Then("I should have the result as follows", ((string)(null)), table14, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Error Code",
                        "Rule"});
            table15.AddRow(new string[] {
                        "FirstName",
                        "ProfileFirstNameMaxLength",
                        ""});
            table15.AddRow(new string[] {
                        "LastName",
                        "ProfileLastNameMaxLength",
                        ""});
#line 79
 testRunner.And("the signup view model should have following errors", ((string)(null)), table15, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Email is invalid")]
        public virtual void EmailIsInvalid()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Email is invalid", ((string[])(null)));
#line 84
this.ScenarioSetup(scenarioInfo);
#line 85
 testRunner.Given("I have not been authenticated yet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "Password Confirm",
                        "First Name",
                        "Last Name"});
            table16.AddRow(new string[] {
                        "hautamatut.by",
                        "ruinruin",
                        "ruinruin",
                        "Vitali",
                        "Hatalski"});
#line 86
 testRunner.When("I fill sign up form with the following data", ((string)(null)), table16, "When ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name",
                        "Message Type"});
            table17.AddRow(new string[] {
                        "hautamatut.by",
                        "Vitali",
                        "Hatalski",
                        "Warning"});
#line 89
 testRunner.Then("I should have the result as follows", ((string)(null)), table17, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Error Code",
                        "Rule"});
            table18.AddRow(new string[] {
                        "Email",
                        "UserEmailInvalid",
                        ""});
#line 92
 testRunner.And("the signup view model should have following errors", ((string)(null)), table18, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Password Confirm does not match")]
        public virtual void PasswordConfirmDoesNotMatch()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Password Confirm does not match", ((string[])(null)));
#line 96
this.ScenarioSetup(scenarioInfo);
#line 97
 testRunner.Given("I have not been authenticated yet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "Password Confirm",
                        "First Name",
                        "Last Name"});
            table19.AddRow(new string[] {
                        "hautama@tut.by",
                        "ruinruin",
                        "ruinruin1",
                        "Vitali",
                        "Hatalski"});
#line 98
 testRunner.When("I fill sign up form with the following data", ((string)(null)), table19, "When ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name",
                        "Message Type"});
            table20.AddRow(new string[] {
                        "hautama@tut.by",
                        "Vitali",
                        "Hatalski",
                        "Warning"});
#line 101
 testRunner.Then("I should have the result as follows", ((string)(null)), table20, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Error Code",
                        "Rule"});
            table21.AddRow(new string[] {
                        "PasswordConfirm",
                        "UserPasswordConfirmNotEqual",
                        ""});
#line 104
 testRunner.And("the signup view model should have following errors", ((string)(null)), table21, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Password length cannot be less than 7 chars")]
        public virtual void PasswordLengthCannotBeLessThan7Chars()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Password length cannot be less than 7 chars", ((string[])(null)));
#line 108
this.ScenarioSetup(scenarioInfo);
#line 109
 testRunner.Given("I have not been authenticated yet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "Password Confirm",
                        "First Name",
                        "Last Name"});
            table22.AddRow(new string[] {
                        "hautama@tut.by",
                        "ruin",
                        "ruin",
                        "Vitali",
                        "Hatalski"});
#line 110
 testRunner.When("I fill sign up form with the following data", ((string)(null)), table22, "When ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name",
                        "Message Type"});
            table23.AddRow(new string[] {
                        "hautama@tut.by",
                        "Vitali",
                        "Hatalski",
                        "Warning"});
#line 113
 testRunner.Then("I should have the result as follows", ((string)(null)), table23, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Error Code",
                        "Rule"});
            table24.AddRow(new string[] {
                        "Password",
                        "UserPasswordLength",
                        ""});
#line 116
 testRunner.And("the signup view model should have following errors", ((string)(null)), table24, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Password length cannot be more than 21 chars")]
        public virtual void PasswordLengthCannotBeMoreThan21Chars()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Password length cannot be more than 21 chars", ((string[])(null)));
#line 120
this.ScenarioSetup(scenarioInfo);
#line 121
 testRunner.Given("I have not been authenticated yet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "Password Confirm",
                        "First Name",
                        "Last Name"});
            table25.AddRow(new string[] {
                        "hautama@tut.by",
                        "passwordwithmorethan21chars",
                        "passwordwithmorethan21chars",
                        "Vitali",
                        "Hatalski"});
#line 122
 testRunner.When("I fill sign up form with the following data", ((string)(null)), table25, "When ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name",
                        "Message Type"});
            table26.AddRow(new string[] {
                        "hautama@tut.by",
                        "Vitali",
                        "Hatalski",
                        "Warning"});
#line 125
 testRunner.Then("I should have the result as follows", ((string)(null)), table26, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Error Code",
                        "Rule"});
            table27.AddRow(new string[] {
                        "Password",
                        "UserPasswordLength",
                        ""});
#line 128
 testRunner.And("the signup view model should have following errors", ((string)(null)), table27, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Password is required and Password Confirm does not match")]
        public virtual void PasswordIsRequiredAndPasswordConfirmDoesNotMatch()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Password is required and Password Confirm does not match", ((string[])(null)));
#line 132
this.ScenarioSetup(scenarioInfo);
#line 133
 testRunner.Given("I have not been authenticated yet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "Password Confirm",
                        "First Name",
                        "Last Name"});
            table28.AddRow(new string[] {
                        "hautama@tut.by",
                        "",
                        "ruinruin",
                        "Vitali",
                        "Hatalski"});
#line 134
 testRunner.When("I fill sign up form with the following data", ((string)(null)), table28, "When ");
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name",
                        "Message Type"});
            table29.AddRow(new string[] {
                        "hautama@tut.by",
                        "Vitali",
                        "Hatalski",
                        "Warning"});
#line 137
 testRunner.Then("I should have the result as follows", ((string)(null)), table29, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Error Code",
                        "Rule"});
            table30.AddRow(new string[] {
                        "Password",
                        "UserPasswordRequired",
                        ""});
            table30.AddRow(new string[] {
                        "PasswordConfirm",
                        "UserPasswordConfirmNotEqual",
                        ""});
#line 140
 testRunner.And("the signup view model should have following errors", ((string)(null)), table30, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
