//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TdService.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminDashboardResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminDashboardResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TdService.Resources.Views.AdminDashboardResources", typeof(AdminDashboardResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator  dashboard.
        /// </summary>
        public static string AdminDashboardPageTitle {
            get {
                return ResourceManager.GetString("AdminDashboardPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AllRoles {
            get {
                return ResourceManager.GetString("AllRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string BtnFindText {
            get {
                return ResourceManager.GetString("BtnFindText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t modify your own roles.
        /// </summary>
        public static string CantModifyOwnRole {
            get {
                return ResourceManager.GetString("CantModifyOwnRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find User By Email.
        /// </summary>
        public static string FindByEmailWaterMark {
            get {
                return ResourceManager.GetString("FindByEmailWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find User By Id.
        /// </summary>
        public static string FindByIdWaterMark {
            get {
                return ResourceManager.GetString("FindByIdWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect page index.
        /// </summary>
        public static string GoToPageIndexValidationMessage {
            get {
                return ResourceManager.GetString("GoToPageIndexValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string GotoPageWatermark {
            get {
                return ResourceManager.GetString("GotoPageWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users found.
        /// </summary>
        public static string NoUsersFound {
            get {
                return ResourceManager.GetString("NoUsersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string PagingText1 {
            get {
                return ResourceManager.GetString("PagingText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string PagingText2 {
            get {
                return ResourceManager.GetString("PagingText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string PrevPage {
            get {
                return ResourceManager.GetString("PrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Administrator can modify users&apos; roles.
        /// </summary>
        public static string RoleManagementPermissionsError {
            get {
                return ResourceManager.GetString("RoleManagementPermissionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string RolesForUser {
            get {
                return ResourceManager.GetString("RolesForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This role can&apos;t be assigned.
        /// </summary>
        public static string ShopperRoleCannotBeAssigned {
            get {
                return ResourceManager.GetString("ShopperRoleCannotBeAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect filter value.
        /// </summary>
        public static string UserFilterValiidationMessage {
            get {
                return ResourceManager.GetString("UserFilterValiidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string UserInfoEmail {
            get {
                return ResourceManager.GetString("UserInfoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string UserInfoFullName {
            get {
                return ResourceManager.GetString("UserInfoFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string UserInfoId {
            get {
                return ResourceManager.GetString("UserInfoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Access Time.
        /// </summary>
        public static string UserInfoLastAccessTime {
            get {
                return ResourceManager.GetString("UserInfoLastAccessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string UserInfoOrders {
            get {
                return ResourceManager.GetString("UserInfoOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        public static string UserInfoPackages {
            get {
                return ResourceManager.GetString("UserInfoPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserInfoUsername {
            get {
                return ResourceManager.GetString("UserInfoUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users per page:.
        /// </summary>
        public static string UsersPerPage {
            get {
                return ResourceManager.GetString("UsersPerPage", resourceCulture);
            }
        }
    }
}
