//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TdService.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashboardViewResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardViewResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TdService.Resources.Views.DashboardViewResources", typeof(DashboardViewResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ActionsHeader {
            get {
                return ResourceManager.GetString("ActionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is required and should be  a number.
        /// </summary>
        public static string AddFundsAmountValidationMessage {
            get {
                return ResourceManager.GetString("AddFundsAmountValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Funds.
        /// </summary>
        public static string AddFundsButton {
            get {
                return ResourceManager.GetString("AddFundsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string AddFundsButtonLoading {
            get {
                return ResourceManager.GetString("AddFundsButtonLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD ITEM.
        /// </summary>
        public static string AddItemButton {
            get {
                return ResourceManager.GetString("AddItemButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add item form.
        /// </summary>
        public static string AddItemForm {
            get {
                return ResourceManager.GetString("AddItemForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Order.
        /// </summary>
        public static string AddOrderButton {
            get {
                return ResourceManager.GetString("AddOrderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Order....
        /// </summary>
        public static string AddOrderButtonLoadingMessage {
            get {
                return ResourceManager.GetString("AddOrderButtonLoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Package.
        /// </summary>
        public static string AddPackageButton {
            get {
                return ResourceManager.GetString("AddPackageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Package....
        /// </summary>
        public static string AddPackageButtonLoadingMessage {
            get {
                return ResourceManager.GetString("AddPackageButtonLoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently on the user {1} page (ID {0})..
        /// </summary>
        public static string AdminViewNoticeMessage {
            get {
                return ResourceManager.GetString("AdminViewNoticeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Funds.
        /// </summary>
        public static string BalanceAddFundsButton {
            get {
                return ResourceManager.GetString("BalanceAddFundsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string BalanceHeader {
            get {
                return ResourceManager.GetString("BalanceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all orders.
        /// </summary>
        public static string CollapseAllOrders {
            get {
                return ResourceManager.GetString("CollapseAllOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all packages.
        /// </summary>
        public static string CollapseAllPackages {
            get {
                return ResourceManager.GetString("CollapseAllPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customs Declaration.
        /// </summary>
        public static string CustomsDeclaration {
            get {
                return ResourceManager.GetString("CustomsDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Any Ware - Dashboard.
        /// </summary>
        public static string DashboardPageTitle {
            get {
                return ResourceManager.GetString("DashboardPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove item.
        /// </summary>
        public static string DeleteItemTitle {
            get {
                return ResourceManager.GetString("DeleteItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string DeliveryHeader {
            get {
                return ResourceManager.GetString("DeliveryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit item.
        /// </summary>
        public static string EditItemTitle {
            get {
                return ResourceManager.GetString("EditItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string ExampleHeader {
            get {
                return ResourceManager.GetString("ExampleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all orders.
        /// </summary>
        public static string ExpandAllOrders {
            get {
                return ResourceManager.GetString("ExpandAllOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all packages.
        /// </summary>
        public static string ExpandAllPackages {
            get {
                return ResourceManager.GetString("ExpandAllPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while confirming your PayPal transaction. Contact adminictrator for details..
        /// </summary>
        public static string FailedPayPalPaymentConfirmationMessage {
            get {
                return ResourceManager.GetString("FailedPayPalPaymentConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string HistoryPackagesTabHeader {
            get {
                return ResourceManager.GetString("HistoryPackagesTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN STOCK.
        /// </summary>
        public static string InStockButton {
            get {
                return ResourceManager.GetString("InStockButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string ItemNameHeader {
            get {
                return ResourceManager.GetString("ItemNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string ItemsTotalHeader {
            get {
                return ResourceManager.GetString("ItemsTotalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait. Loading your orders history...
        /// </summary>
        public static string LoadingHistoryOrdersMessage {
            get {
                return ResourceManager.GetString("LoadingHistoryOrdersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait. Loading your packages history...
        /// </summary>
        public static string LoadingHistoryPackagesMessage {
            get {
                return ResourceManager.GetString("LoadingHistoryPackagesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait. Loading your recent orders...
        /// </summary>
        public static string LoadingRecentOrdersMessage {
            get {
                return ResourceManager.GetString("LoadingRecentOrdersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait. Loading your recent packages...
        /// </summary>
        public static string LoadingRecentPackagesMessage {
            get {
                return ResourceManager.GetString("LoadingRecentPackagesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move all order items to package.
        /// </summary>
        public static string MoveAllItemsTitle {
            get {
                return ResourceManager.GetString("MoveAllItemsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move item to package.
        /// </summary>
        public static string MoveItemTitle {
            get {
                return ResourceManager.GetString("MoveItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to a new package.
        /// </summary>
        public static string MoveToNewPackage {
            get {
                return ResourceManager.GetString("MoveToNewPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShopAnyWare address.
        /// </summary>
        public static string MyUsAddressHeader {
            get {
                return ResourceManager.GetString("MyUsAddressHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.S. address.
        /// </summary>
        public static string MyUsAddressLinkMessage {
            get {
                return ResourceManager.GetString("MyUsAddressLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the link to see your U.S. address.
        /// </summary>
        public static string MyUsAddressLinkTooltip {
            get {
                return ResourceManager.GetString("MyUsAddressLinkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter shop name or url (ex. amazon.com).
        /// </summary>
        public static string NewOrderPlaceholder {
            get {
                return ResourceManager.GetString("NewOrderPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter package name (ex. my package).
        /// </summary>
        public static string NewPackagePlaceholder {
            get {
                return ResourceManager.GetString("NewPackagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no orders that were processed..
        /// </summary>
        public static string NoHistoryOrdersMessage {
            get {
                return ResourceManager.GetString("NoHistoryOrdersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no packages that were delivered to you..
        /// </summary>
        public static string NoHistoryPackagesMessage {
            get {
                return ResourceManager.GetString("NoHistoryPackagesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The items will be automatically displayed when the order is received and processed by operator..
        /// </summary>
        public static string NoItemsMessage {
            get {
                return ResourceManager.GetString("NoItemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no orders to show. Please add a new one..
        /// </summary>
        public static string NoOrdersMessage {
            get {
                return ResourceManager.GetString("NoOrdersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no items inside this package. Please move the items from orders..
        /// </summary>
        public static string NoPackageItemsMessage {
            get {
                return ResourceManager.GetString("NoPackageItemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no packages to show. Please add a new one..
        /// </summary>
        public static string NoPackagesMessage {
            get {
                return ResourceManager.GetString("NoPackagesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no transactions to show..
        /// </summary>
        public static string NoTransactionsMessage {
            get {
                return ResourceManager.GetString("NoTransactionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order cannot be removed in current state..
        /// </summary>
        public static string OrderCannotBeRemoved {
            get {
                return ResourceManager.GetString("OrderCannotBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string OrderCreatedDateHeader {
            get {
                return ResourceManager.GetString("OrderCreatedDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order has been successfully added..
        /// </summary>
        public static string OrderCreatedSuccess {
            get {
                return ResourceManager.GetString("OrderCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string OrderIdHeader {
            get {
                return ResourceManager.GetString("OrderIdHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order #.
        /// </summary>
        public static string OrderNumberHeader {
            get {
                return ResourceManager.GetString("OrderNumberHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter order number.
        /// </summary>
        public static string OrderNumberPlaceholder {
            get {
                return ResourceManager.GetString("OrderNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request For Orders.
        /// </summary>
        public static string OrderOption1 {
            get {
                return ResourceManager.GetString("OrderOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Orders.
        /// </summary>
        public static string OrderOption2 {
            get {
                return ResourceManager.GetString("OrderOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string OrderReceivedDateHeader {
            get {
                return ResourceManager.GetString("OrderReceivedDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order has been successfully removed..
        /// </summary>
        public static string OrderRemovedSuccess {
            get {
                return ResourceManager.GetString("OrderRemovedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned.
        /// </summary>
        public static string OrderReturnedDateHeader {
            get {
                return ResourceManager.GetString("OrderReturnedDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string OrdersHeader {
            get {
                return ResourceManager.GetString("OrdersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package cannot be removed in current state..
        /// </summary>
        public static string PackageCannotBeRemoved {
            get {
                return ResourceManager.GetString("PackageCannotBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string PackageCreatedDateHeader {
            get {
                return ResourceManager.GetString("PackageCreatedDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package has been successfully created..
        /// </summary>
        public static string PackageCreatedSuccessMessage {
            get {
                return ResourceManager.GetString("PackageCreatedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        public static string PackageDeliveredDateHeader {
            get {
                return ResourceManager.GetString("PackageDeliveredDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatched.
        /// </summary>
        public static string PackageDispatchedDateHeader {
            get {
                return ResourceManager.GetString("PackageDispatchedDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PackageNameHeader {
            get {
                return ResourceManager.GetString("PackageNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package has been successfully removed..
        /// </summary>
        public static string PackageRemovedSuccess {
            get {
                return ResourceManager.GetString("PackageRemovedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        public static string PackagesHeader {
            get {
                return ResourceManager.GetString("PackagesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment / PayPal.
        /// </summary>
        public static string PaymentTypePaypal {
            get {
                return ResourceManager.GetString("PaymentTypePaypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string PriceHeader {
            get {
                return ResourceManager.GetString("PriceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to edit item price..
        /// </summary>
        public static string PriceTitle {
            get {
                return ResourceManager.GetString("PriceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string QuantityHeader {
            get {
                return ResourceManager.GetString("QuantityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Packages.
        /// </summary>
        public static string RecentPackagesTabHeader {
            get {
                return ResourceManager.GetString("RecentPackagesTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOVE.
        /// </summary>
        public static string RemoveOrderButton {
            get {
                return ResourceManager.GetString("RemoveOrderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return item back to order.
        /// </summary>
        public static string ReturnItemBackTitle {
            get {
                return ResourceManager.GetString("ReturnItemBackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETURN.
        /// </summary>
        public static string ReturnOrderButton {
            get {
                return ResourceManager.GetString("ReturnOrderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string SaveChangesButton {
            get {
                return ResourceManager.GetString("SaveChangesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND PACKAGE.
        /// </summary>
        public static string SendPackageButton {
            get {
                return ResourceManager.GetString("SendPackageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusHeader {
            get {
                return ResourceManager.GetString("StatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payment has been successfullt processed!.
        /// </summary>
        public static string SuccessfullPayPalPaymentConfirmationMessage {
            get {
                return ResourceManager.GetString("SuccessfullPayPalPaymentConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COST.
        /// </summary>
        public static string TotalCostHeader {
            get {
                return ResourceManager.GetString("TotalCostHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string TotalWeightHeader {
            get {
                return ResourceManager.GetString("TotalWeightHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking #.
        /// </summary>
        public static string TrackingNumberHeader {
            get {
                return ResourceManager.GetString("TrackingNumberHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter tracking number.
        /// </summary>
        public static string TrackingNumberPlaceholder {
            get {
                return ResourceManager.GetString("TrackingNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string TransactionsAmount {
            get {
                return ResourceManager.GetString("TransactionsAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string TransactionsDate {
            get {
                return ResourceManager.GetString("TransactionsDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string TransactionsStatus {
            get {
                return ResourceManager.GetString("TransactionsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TransactionsType {
            get {
                return ResourceManager.GetString("TransactionsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string WeightHeader {
            get {
                return ResourceManager.GetString("WeightHeader", resourceCulture);
            }
        }
    }
}
