//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TdService.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeViewResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeViewResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TdService.Resources.Views.HomeViewResources", typeof(HomeViewResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy what you want from the USA and get your merchandise delivered to your home address in CIS countries within a week..
        /// </summary>
        public static string PageHeroDescription {
            get {
                return ResourceManager.GetString("PageHeroDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop any ware online in the USA!.
        /// </summary>
        public static string PageHeroHeader {
            get {
                return ResourceManager.GetString("PageHeroHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Join us &amp; get your USA address.
        /// </summary>
        public static string ServiceDescriptionHeader1 {
            get {
                return ResourceManager.GetString("ServiceDescriptionHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Shop any ware in the USA.
        /// </summary>
        public static string ServiceDescriptionHeader2 {
            get {
                return ResourceManager.GetString("ServiceDescriptionHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Receive your packages.
        /// </summary>
        public static string ServiceDescriptionHeader3 {
            get {
                return ResourceManager.GetString("ServiceDescriptionHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration at ShopAnyWare is free. Within minutes of completing your registration, you will receive your new dedicated USA street address in New Jersey, New York.  You will now be able to use this address for all your USA shopping. Its time to start shopping!.
        /// </summary>
        public static string ServiceDescriptionValue1 {
            get {
                return ResourceManager.GetString("ServiceDescriptionValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop at thousands of online shopping sites in the USA including auction sites like Ebay.com, famous name brand stores such as Saks Fifth Avenue, and small independent retailers like Etsy.com. It does not matter if the the store only ships inside the USA or only accepts USA credit cards, as a ShopAnyWare Member you can now shop wherever you would like with access to the US merchant&apos;s full product offerings as well as the best pricing!.
        /// </summary>
        public static string ServiceDescriptionValue2_1 {
            get {
                return ResourceManager.GetString("ServiceDescriptionValue2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop at US websites like you usually would and use your ShopAnyWare address as your &quot;Ship To&quot; address..
        /// </summary>
        public static string ServiceDescriptionValue2_2 {
            get {
                return ResourceManager.GetString("ServiceDescriptionValue2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can set a courier preference or we will automatically select the fastest &amp; least expensive courier option (USPS or Major Express) for you on each shipment..
        /// </summary>
        public static string ServiceDescriptionValue3 {
            get {
                return ResourceManager.GetString("ServiceDescriptionValue3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every package is repackaged and where applicable multiple-store orders are consolidated into the same package to save you money..
        /// </summary>
        public static string ServiceDescriptionValue3_1 {
            get {
                return ResourceManager.GetString("ServiceDescriptionValue3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All customs documentation are completed for you..
        /// </summary>
        public static string ServiceDescriptionValue3_2 {
            get {
                return ResourceManager.GetString("ServiceDescriptionValue3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All merchandise is insured unless you prefer otherwise..
        /// </summary>
        public static string ServiceDescriptionValue3_3 {
            get {
                return ResourceManager.GetString("ServiceDescriptionValue3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A full range of packing options - you can even specify whether to keep or discard original shoe boxes!.
        /// </summary>
        public static string ServiceDescriptionValue3_4 {
            get {
                return ResourceManager.GetString("ServiceDescriptionValue3_4", resourceCulture);
            }
        }
    }
}
