//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TdService.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OurServiceViewResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OurServiceViewResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TdService.Resources.Views.OurServiceViewResources", typeof(OurServiceViewResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free repackaging to minimize dim weight.
        /// </summary>
        public static string FastDelivery1 {
            get {
                return ResourceManager.GetString("FastDelivery1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free consolidation of multiple-store orders.
        /// </summary>
        public static string FastDelivery2 {
            get {
                return ResourceManager.GetString("FastDelivery2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Pre-shipment Screening for wrong, broken or prohibited items.
        /// </summary>
        public static string FastDelivery3 {
            get {
                return ResourceManager.GetString("FastDelivery3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Customs Documentation.
        /// </summary>
        public static string FastDelivery4 {
            get {
                return ResourceManager.GetString("FastDelivery4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand-delivery via USPS or Major Express.
        /// </summary>
        public static string FastDelivery5 {
            get {
                return ResourceManager.GetString("FastDelivery5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save 80% on International Shipping and get your goods faster with 2-4 day delivery worldwide!.
        /// </summary>
        public static string FastDeliveryHeader {
            get {
                return ResourceManager.GetString("FastDeliveryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the US store only accepts US payment.. Our Personal Shoppers can buy it for you..
        /// </summary>
        public static string OperatorService1 {
            get {
                return ResourceManager.GetString("OperatorService1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insider Guides to the hottest US stores, trends and products..
        /// </summary>
        public static string OperatorService2 {
            get {
                return ResourceManager.GetString("OperatorService2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the Best with our Concierge Shopping Services.
        /// </summary>
        public static string OperatorServiceHeader {
            get {
                return ResourceManager.GetString("OperatorServiceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Services.
        /// </summary>
        public static string OurServiceHeader {
            get {
                return ResourceManager.GetString("OurServiceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many USA stores will not ship to people outside the USA or charge very high fees to do so..
        /// </summary>
        public static string OwnAddress2 {
            get {
                return ResourceManager.GetString("OwnAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With ShopAnyWare you get your very own US address enabling you to purchase from any US website..
        /// </summary>
        public static string OwnAddress3 {
            get {
                return ResourceManager.GetString("OwnAddress3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simply buy what you want, have it shipped to your ShopAnyWare Address and we ship it to you anywhere in the world..
        /// </summary>
        public static string OwnAddress4 {
            get {
                return ResourceManager.GetString("OwnAddress4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With ShopAnyWare you can buy from any US Store with your own US address.
        /// </summary>
        public static string OwnAddressHeader {
            get {
                return ResourceManager.GetString("OwnAddressHeader", resourceCulture);
            }
        }
    }
}
